### ISSUE TITLE
Upgrade Python RTM version to 0.4.0

### ISSUE THREAD

**Issue by mikegrima** [Netflix/hubcommander#1]
Need to upgrade the RTM-bot to 0.4.0: https://github.com/slackhq/python-rtmbot/releases/tag/0.4.0

I initially had issues with this release, so relied on 0.3.0 for OSS. 0.4.0 is breaking, so will need to make some changes.

**Comment by bboe** [comment]
I started looking at this project today up this project today, and really like the plugin architecture used by RTM 0.4.0. I'm wondering if upgrading is on the roadmap at all. I'd like to use hubcommander with that version, and could convert things for my needs, but it looks like doing so would require a pretty massive pull request to incorporate those changes to hubcommander.

**Comment by mikegrima** [comment]
Hello @bboe : Yes, upgrading to 0.4.0 is certainly on my radar.  I *hope* it won't be a major pull request?

When I was last working with it, I had a number of odd virtual environment issues that I did not have enough time to investigate.

Have you had good experiences with 0.4.0?

**Comment by bboe** [comment]
It's actually not as bad as I initially thought. I was under the assumption that all the plugins were rtmbot plugins themselves, but they're not. I'll make an initial PR hopefully within an hour.
