### ISSUE TITLE
Protect master by default, with support for disabling protection

### ISSUE THREAD

**Issue by lorin** [Netflix/hubcommander#14]
### Feature request

When a new repo is created, default to protected the master branch from being force-pushed or deleted. Provide a command for disabling / re-enabling this protection.

**Comment by mikegrima** [comment]
To add to this -- we should add a command that allows you to protect branches.

**Comment by mikegrima** [comment]
Will need to just make a protected branch feature as well.

**Comment by mikegrima** [comment]
@lorin : Unfortunately, this cannot be completed during the initial create repo request.

When the repository is created, there are no branches. Branches only get created on the initial git push.  However, I have now merged in a very basic branch protection feature, so you can now run that after you create your repo and push some code to it.
