### ISSUE TITLE
Make hubcommander a generic bot framework

### ISSUE THREAD

**Issue by goduncan** [Netflix/hubcommander#34]
I have been using hubcommander internally to run some bot commands without the github component. Would you be interested in not enabling the github plugin by default and turning hubcommander into a generic python slack bot framework? (Would be happy to submit a PR if it is!).

**Comment by mikegrima** [comment]
Hello @goduncan !  I would certainly be interested in seeing a PR for this. You're not the first to request this.

**Comment by goduncan** [comment]
Cool - I just submitted a PR for some of the changes I had made already let me know what you think.

And, thanks for opening this up it is a really useful project.

**Comment by mikegrima** [comment]
Closed via #35
