### ISSUE TITLE
Support Slack Threads

### ISSUE THREAD

**Issue by mikegrima** [Netflix/hubcommander#55]
Need to add support for Slack threading.

This could prove useful to reducing verbose messaging in the channels.

**Comment by sgedward** [comment]
Hi, I saw this problem on Hacktoberfest. looking into the docs. Thanks!

**Comment by mikegrima** [comment]
Hello @sgedward !  Contributions are very much welcome!

**Comment by alxbxbx** [comment]
I have one general question. If someone applies to work on some issue, does that mean that others can't? And it is possible, the fastest one with pull request will close story?

**Comment by mikegrima** [comment]
@alxbxbx Unless @sgedward is submitting a PR, you are welcome to work on this.

**Comment by alxbxbx** [comment]
Great, thanks!

**Comment by knightcube** [comment]
where do i find the docs?

**Comment by sgedward** [comment]
@majinwala  really sorry for the delayed. caught up with some school work.

**Comment by sgedward** [comment]
@mikegrima  really sorry for the delayed. I submitted a pull request.  When I initially started, one of the tests failed: `from testfixtures import LogCapture`. I wonder if I was set up wrong?

**Comment by mikegrima** [comment]
I'm not familiar with `LogCapture`.  Were you working on the logging PR?

**Comment by mikegrima** [comment]
Merged in #65
